### ISSUE TITLE
Error with parse_db attribute

### ISSUE THREAD

**Issue by dfir-man131** [lxndrblz/forensicsim#12]
Any idea why this is presenting an error? I have installed the shared python3 module.

![image](https://user-images.githubusercontent.com/79167752/197849716-66cd583c-a67e-411b-9beb-24897d4e0364.png)

**Comment by lxndrblz** [comment]
@dfir-man131 Hi there, no need to install the shared module, as the scripts only imports a local module named shared.

To get the script working, simply download the complete source code, cd into the utils directory and execute the dump script. Commonly this error occurs, if you don't execute the script from the folder, where the shared.py script is located.
