### ISSUE TITLE
"there could be this many dbs, but I don't support it yet" error was occured.

### ISSUE THREAD

**Issue by kenichi-kobayashi** [lxndrblz/forensicsim#13]
I read the Teams log and got the following error

![image](https://user-images.githubusercontent.com/47070699/215485787-113cddf3-f58c-4bbd-b188-609ff0d80341.png)

Do you know what caused it?

**Comment by lxndrblz** [comment]
Hi @kenichi-kobayashi,

Thanks for bringing this issue up.

Based on your responses I recon that this an issue which seems to appear with more recent installations of Microsoft Teams.

As this parser uses a [Third Party Library](https://github.com/cclgroupltd/ccl_chrome_indexeddb/blob/master/ccl_chromium_indexeddb.py) for processing the databases it self, some implementation might be necessary. Unfortunately, I do not have a data sample that allows me to reproduce this issue. If anyone could provide me one, I would look into it.
