### ISSUE TITLE
Where to find .leveldb file

### ISSUE THREAD

**Issue by faniAhmed** [lxndrblz/forensicsim#14]
I have two Teams desktop app installed, one is the business or work teams distribution and the other is personal use teams distribution. I have found db file for the business/work one but I could not found any db for the personal use teams distribution.
The business/word distribution has the following path 
````
C:\\Users\\Farhan Ahmed\\AppData\\Roaming\\Microsoft\\Teams\\IndexedDB\\https_teams.live.com_0.indexeddb.leveldb
````
The Microsoft Teams personal use distribution is being installed as Windows app and I do not know where it's .leveldb file is

**Comment by KarelZe** [comment]
Thanks for your question and sorry for the late reply🥶 Mine is under `C:\Users\Markus\AppData\Local\Packages\MicrosoftTeams_8wekyb3d8bbwe\LocalCache\Microsoft\MSTeams\EBWebView\Default\IndexedDB\https_teams.live.com_0.indexeddb.leveldb`.
