### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by liamrb123** [lxndrblz/forensicsim#15]
I followed all the instructions , but when I start Autopsy, It does not show anything under results.

**Comment by lxndrblz** [comment]
Thanks for taking the effort to open up an issue. Unfortunately, without any further details I can not assist you. Going to close this for now.

**Comment by liamrb123** [comment]
hello, sorry I completely forgot i posted an issue. 
I downloaded the files and put them into the correct folders and followed the instructions. but when I use autopsy, none of the results come up as they should. Everything is downloaded into the correct file but it's as if the download doesn't work.
