### ISSUE TITLE
"there could be this many dbs, but I don't support it yet" error was occured.

### ISSUE THREAD

**Issue by jwilp** [lxndrblz/forensicsim#20]
Does not seem to work with newer versions of TEAMS. Please update this awesome tool! You will be doing a great service for an ongoing case we have. Kind regards.

**Comment by lxndrblz** [comment]
I am currently working on a solution, which I am trying to push to the upstream library that we use for processing the IndexedDB files. The issue can be followed here:

https://github.com/cclgroupltd/ccl_chrome_indexeddb/issues/18

I want to be clear that the error you are seing has to do something with how the metadata (if lots of object stores are prest) is read and not necessarily something with the Teams version that is in use.

**Comment by cclgroupltd** [comment]
@lxndrblz this should be fixed in the latest commit in our repo - let me know how you get on.
