### ISSUE TITLE
Update forensics.im for simplified installation process 🆕

### ISSUE THREAD

**Issue by KarelZe** [lxndrblz/forensicsim#46]
With #40 we added a zip to the release for easier use in autopys. `Forensicsim_Parser.py` and  `ms_teams_parser.exe` are now released in `forensicsim.zip`. 

@lxndrblz  please also update https://forensics.im/blog/installing-forensicsim-module/ to be consistent with `README.md`.

**Comment by lxndrblz** [comment]
@KarelZe Documentation has been updated:

https://forensics.im/blog/installing-forensicsim-module/
