### ISSUE TITLE
[please import that ] [Certain Database IDs get missed]

### ISSUE THREAD

**Issue by seychelles111** [lxndrblz/forensicsim#59]
https://github.com/cclgroupltd/ccl_chrome_indexeddb/issues/18
https://github.com/cclgroupltd/ccl_chrome_indexeddb/commit/0b80ecd05bfb14213237a4b9f433ed7f74f2a3a4

thank , please add

**Comment by lxndrblz** [comment]
This Issue is a duplicate to the issues #13  and #20. It will be addressed in PR #36.
