### ISSUE TITLE
feat: Integrate other Electron-based Messenger

### ISSUE THREAD

**Issue by lxndrblz** [lxndrblz/forensicsim#6]
Currently, there is a larger number of Electron-based Messaging Apps that could be extracted in similar fashion to Microsoft Teams, including the following applications:
* Discord
* WhatsApp
* Zalo
* Slack
* Twist

I would be able to create a base class and extend it for the individual messengers. The output should be following a common layout to allow reuse of the existing Autopsy code.

**Comment by faniAhmed** [comment]
Thanks for helping the community. I want to ask that when will the WhatsApp Forensic part complete. An estimated date would be great.

**Comment by lxndrblz** [comment]
@faniAhmed I had extensively looked at WhatsApp before, but I was able to recover only metadata. That's why I think it won't be coming any time soon.

**Comment by faniAhmed** [comment]
@lxndrblz  Have you looked in this folder
```
C:\Users\Farhan Ahmed\AppData\Local\Packages\5319275A.WhatsAppDesktop_cv1g1gvanyjgm\LocalState
```
It contains encrypted messages.db and contacts.db files. From what I have learned it is encrypted through AES-256 and key is stored in Windows credential manager. I tried to get the key from credential manager but failed in doing so.

**Comment by lxndrblz** [comment]
Due to lack of time and prioritization of other projects this issue will no longer be pursuit.
