### ISSUE TITLE
[request] option to archive pictures ? 

### ISSUE THREAD

**Issue by seychelles111** [lxndrblz/forensicsim#63]
Hello I really need to archive my Teams chats, my employe-er might actually delete my account, while they release me on a "vacation without pay", for half a year... which might end in a termination later, and in the short term, someone actual confusing my account and delete it.

Im confused, if I the files themselves could be saved some how... ie pictures or whatever... 
I just dont wanna lose my chats... its so annoying... everyone that leaves, I am losing backlogs of chats... which does distruct things, as things that happens weeks or months ago matter.. also re-evaluing , what you had done is important... and if I were in 2019 it wouldbt been so easy to archive,  yet I cannot use the other tools..  _only this localdb thing_ which is only chats right?

**Comment by lxndrblz** [comment]
This solution does not allow to recover images or other other files.

You might be able to recover them from the Chromium Cache with a tool such as the NirSoft Cache Viewer.
