### ISSUE TITLE
[request] HTML output support, via the CMD line

### ISSUE THREAD

**Issue by seychelles111** [lxndrblz/forensicsim#64]

**Comment by lxndrblz** [comment]
Hi there,

the JSON outputs contains the HTML formatting of the individual messages. Hence, by processing the JSON output you can easily assemble back an HTML report. The main purpose of this solution is to integrate with Autopsy and therefore I do not consider a HTML report worth the effort of implementation.   

Please refrain from opening in-descriptive issues, such as the current one, in the future. For a small project like this, they cause more nuisance than good.
