### ISSUE TITLE
Error loading module 0.81

### ISSUE THREAD

**Issue by wkcoop** [lxndrblz/forensicsim#73]
Hello
I am having problems loading the module using Autopsy 
Details are as follows:
- Autopsy version Autopsy 4.21.0
- Forensicsim version 0.81
- Windows version Microsoft Windows [Version 10.0.19045.3930]
- Virtual machine - 2 cores, 8GB RAM

I have attached a screenshot and the Autopsy log
Feel free to contact me for any further information needed to solve this issue

WKC

[autopsy.log](https://github.com/lxndrblz/forensicsim/files/14078961/autopsy.log)
 [
![error](https://github.com/lxndrblz/forensicsim/assets/158006709/64ff9b23-8cb1-429c-a6a2-1c4acc290aa2)
](url)

**Comment by lxndrblz** [comment]
Hi @wkcoop, 

Can you Please tryo remove the `-> None` from the init method in the Forensicim_Parser.py file and see if that fies your error?

Thanks.
