### ISSUE TITLE
Where is the IndexedDB folder?

### ISSUE THREAD

**Issue by AdonisLeavis** [lxndrblz/forensicsim#89]
I am using Windows 11 Teams (version 24151.2105.2943.2101).
In this case, I was unable to find the file path where IndexedDB is stored.

Could you please tell me where it is saved?

**Comment by lxndrblz** [comment]
> I am using Windows 11 Teams (version 24151.2105.2943.2101).
> In this case, I was unable to find the file path where IndexedDB is stored.
> 
> Could you please tell me where it is saved?

Try the following location:
C:\Users\<username>\AppData\Local\Packages\MSTeams_8wekyb3d8bbwe\LocalCache\Microsoft\MSTeams\EBWebView\WV2Profile_tfw\IndexedDB\https_teams.microsoft.com_0.indexeddb.leveldb
