### ISSUE TITLE
Plugin not work

### ISSUE THREAD

**Issue by aqqsi1337** [lxndrblz/forensicsim#9]
I put plugin dir in `Roaming\autopsy\python_modules\forensicsim` but it not work when i choose it to analyze `Teams` dir
![image](https://user-images.githubusercontent.com/89452910/170623891-d55ba6c1-c484-4a63-871e-9bb273864fe6.png)
![image](https://user-images.githubusercontent.com/89452910/170623782-453a628f-8f4c-44a7-af2d-35e6d00feb1c.png)

**Comment by lxndrblz** [comment]
Would you mind sharing the autopsy log to see if there were any errors when you ran the module?

**Comment by lxndrblz** [comment]
Closed due to lack of response.
